grafana:
  adminPassword: "ChangeMe123!"   # consider using a secret instead (see below)
  persistence:
    enabled: false
  service:
    type: LoadBalancer

prometheus:
  prometheusSpec:
    retention: 24h
    storageSpec: {}               # <- empty = no PVC
  service:
    type: LoadBalancer

alertmanager:
  persistence:
    enabled: false
  service:
    type: LoadBalancer

# EKS tip: these are not exposed on EKS control plane; disabling avoids scrape noise
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
