apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: { name: fluent-bit }
rules:
  - apiGroups: [""]
    resources: ["pods","namespaces"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata: { name: fluent-bit }
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit
subjects:
  - kind: ServiceAccount
    name: fluent-bit
    namespace: logging
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
  labels: { app: fluent-bit }
spec:
  selector:
    matchLabels: { app: fluent-bit }
  template:
    metadata:
      labels: { app: fluent-bit }
    spec:
      serviceAccountName: fluent-bit
      tolerations:
        - operator: Exists
      containers:
        - name: fluent-bit
          image: docker.io/fluent/fluent-bit:2.2
          resources:
            requests: { cpu: 50m, memory: 64Mi }
            limits:   { cpu: 200m, memory: 256Mi }
          volumeMounts:
            - { name: varlog, mountPath: /var/log }
            - { name: varlibdocker, mountPath: /var/lib/docker/containers, readOnly: true }
          env:
            - { name: FLUENT_ELASTICSEARCH_HOST, value: "elasticsearch.logging.svc.cluster.local" }
            - { name: FLUENT_ELASTICSEARCH_PORT, value: "9200" }
          args:
            - -i
            - tail
            - -p
            - path=/var/log/containers/*.log
            - -o
            - es
            - -p
            - "host=$(FLUENT_ELASTICSEARCH_HOST)"
            - -p
            - "port=$(FLUENT_ELASTICSEARCH_PORT)"
            - -p
            - index=fluentbit
      volumes:
        - { name: varlog, hostPath: { path: /var/log } }
        - { name: varlibdocker, hostPath: { path: /var/lib/docker/containers } }
