apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: logging
spec:
  replicas: 1
  selector: { matchLabels: { app: kibana } }
  template:
    metadata: { labels: { app: kibana } }
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.14.3
          env:
            - { name: ELASTICSEARCH_HOSTS, value: "http://elasticsearch.logging.svc.cluster.local:9200" }
          ports:
            - containerPort: 5601
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logging
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector: { app: kibana }
  ports:
    - { name: http, port: 5601, targetPort: 5601 }
